/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.carrerareelevos;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;

/**
 * @author Duvan Poveda
 * Frame que se encarga de manejar el aspecto grafico del programa
 */
public class FrameCarrera extends javax.swing.JFrame {

    /**
     * Creates new form FrameCarrera
     */
    public FrameCarrera() {
        initComponents();
    }
    public JLabel getCorredorAA(){
        return corredorAA;
    }
    public JLabel getCorredorBA(){
        return CorredorBA;
    }
    public JLabel getCorredorCA(){
        return CorredorCA;
    }
    public JLabel getNivel1(){
        return Nivel1;
    }
    public JLabel getcorredorAB(){
        return corredorAB;
    }
    public JLabel getcorredorBB(){
        return corredorBB;
    }
    public JLabel getcorredorCB(){
        return corredorCB;
    }
    public JLabel getNivel2(){
        return Nivel2;
    }
        public JLabel getCorredorAC(){
        return corredorAC;
    }
    public JLabel getCorredorBC(){
        return corredorBC;
    }
    public JLabel getCorredorCC(){
        return corredorCC;
    }
    public JLabel getNivel3(){
        return Nivel3;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        corredorAA = new javax.swing.JLabel();
        CorredorBA = new javax.swing.JLabel();
        Nivel1 = new javax.swing.JLabel();
        Nivel2 = new javax.swing.JLabel();
        CorredorCA = new javax.swing.JLabel();
        corredorAB = new javax.swing.JLabel();
        corredorCB = new javax.swing.JLabel();
        corredorBB = new javax.swing.JLabel();
        Nivel3 = new javax.swing.JLabel();
        corredorAC = new javax.swing.JLabel();
        corredorBC = new javax.swing.JLabel();
        corredorCC = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        BtnIniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        corredorAA.setIcon(new javax.swing.ImageIcon("C:\\Users\\dalej\\OneDrive\\Documents\\NetBeansProjects\\CarreraReelevos\\descarga.png")); // NOI18N

        CorredorBA.setIcon(new javax.swing.ImageIcon("C:\\Users\\dalej\\OneDrive\\Documents\\NetBeansProjects\\CarreraReelevos\\descarga.png")); // NOI18N

        Nivel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 2));

        Nivel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 2));

        CorredorCA.setIcon(new javax.swing.ImageIcon("C:\\Users\\dalej\\OneDrive\\Documents\\NetBeansProjects\\CarreraReelevos\\descarga.png")); // NOI18N

        corredorAB.setIcon(new javax.swing.ImageIcon("C:\\Users\\dalej\\OneDrive\\Documents\\NetBeansProjects\\CarreraReelevos\\descarga.png")); // NOI18N

        corredorCB.setIcon(new javax.swing.ImageIcon("C:\\Users\\dalej\\OneDrive\\Documents\\NetBeansProjects\\CarreraReelevos\\descarga.png")); // NOI18N

        corredorBB.setIcon(new javax.swing.ImageIcon("C:\\Users\\dalej\\OneDrive\\Documents\\NetBeansProjects\\CarreraReelevos\\descarga.png")); // NOI18N

        Nivel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2));

        corredorAC.setIcon(new javax.swing.ImageIcon("C:\\Users\\dalej\\OneDrive\\Documents\\NetBeansProjects\\CarreraReelevos\\descarga.png")); // NOI18N

        corredorBC.setIcon(new javax.swing.ImageIcon("C:\\Users\\dalej\\OneDrive\\Documents\\NetBeansProjects\\CarreraReelevos\\descarga.png")); // NOI18N

        corredorCC.setIcon(new javax.swing.ImageIcon("C:\\Users\\dalej\\OneDrive\\Documents\\NetBeansProjects\\CarreraReelevos\\descarga.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(corredorAA)
                    .addComponent(CorredorBA)
                    .addComponent(CorredorCA))
                .addGap(128, 128, 128)
                .addComponent(Nivel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(corredorAB)
                    .addComponent(corredorCB)
                    .addComponent(corredorBB))
                .addGap(181, 181, 181)
                .addComponent(Nivel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(corredorAC)
                    .addComponent(corredorBC)
                    .addComponent(corredorCC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addComponent(Nivel3))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Nivel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Nivel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Nivel3, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(corredorAA, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CorredorBA)
                        .addGap(18, 18, 18)
                        .addComponent(CorredorCA))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(corredorAB, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(corredorBB, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(corredorCB, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(corredorAC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(corredorBC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(corredorCC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        corredorAA.getAccessibleContext().setAccessibleName("jLabel1");
        Nivel2.getAccessibleContext().setAccessibleName("jLabel6");

        jLabel1.setText("Carrera");

        BtnIniciar.setText("Comenzar");
        BtnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(BtnIniciar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addComponent(jLabel1)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(BtnIniciar)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * En este metodo se inicializan los hilos principales y cada locacion de los corredores
     */
    private void BtnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIniciarActionPerformed
        // TODO add your handling code here:
        corredorAA.setLocation(0,corredorAA.getLocation().y);
        CorredorBA.setLocation(0,CorredorBA.getLocation().y);
        CorredorCA.setLocation(0,CorredorCA.getLocation().y);
        corredorAB.setLocation(180,corredorAB.getLocation().y);
        corredorBB.setLocation(180,corredorBB.getLocation().y);
        corredorCB.setLocation(180,corredorCB.getLocation().y);
        corredorAC.setLocation(420,corredorAC.getLocation().y);
        corredorBC.setLocation(420,corredorBC.getLocation().y);
        corredorCC.setLocation(420,corredorCC.getLocation().y);
        Carrera hilo1 = new Carrera(corredorAA,this);
        Carrera hilo2 = new Carrera(CorredorBA,this);
        Carrera hilo3 = new Carrera(CorredorCA,this);
        
        hilo1.start();
        hilo2.start();
        hilo3.start();
      
    }//GEN-LAST:event_BtnIniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameCarrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameCarrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameCarrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameCarrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameCarrera().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnIniciar;
    private javax.swing.JLabel CorredorBA;
    private javax.swing.JLabel CorredorCA;
    private javax.swing.JLabel Nivel1;
    private javax.swing.JLabel Nivel2;
    private javax.swing.JLabel Nivel3;
    private javax.swing.JLabel corredorAA;
    private javax.swing.JLabel corredorAB;
    private javax.swing.JLabel corredorAC;
    private javax.swing.JLabel corredorBB;
    private javax.swing.JLabel corredorBC;
    private javax.swing.JLabel corredorCB;
    private javax.swing.JLabel corredorCC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
